### ISSUE TITLE
Apple2driver does not find GPIOs any more after upgrade to Debian 12

### ISSUE THREAD

**Issue by JPT77** [tjboldt/Apple2-IO-RPi#154]
### What happened?

Hi, 

after upgrading to Debian 12 the apple2driver does not want to come up any more. 
how does it access the GPIO hardware?

	Generating Drive in memory from: /home/jan/Apple2-IO-RPi/RaspberryPi/driveimage
	Starting Apple II RPi v002B...
	panic: failed to open gpio
	goroutine 1 [running]:
	github.com/tjboldt/Apple2-IO-RPi/RaspberryPi/apple2driver/a2io.A2Gpio.Init({})
			/home/jan/Apple2-IO-RPi/RaspberryPi/apple2driver/a2io/gpio.go:54 +0x500
	main.main()
			/home/jan/Apple2-IO-RPi/RaspberryPi/apple2driver/driver.go:50 +0xe8
	apple2driver.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
	apple2driver.service: Failed with result 'exit-code'.

I checked everything I could think of, but I found no problem:

	$ ll /dev/gpio*
	crw-rw---- 1 root gpio 254, 0 Nov 19 18:17 /dev/gpiochip0
	crw-rw---- 1 root gpio 254, 1 Nov 19 18:17 /dev/gpiochip1
	crw-rw---- 1 root gpio 241, 0 Nov 20 12:15 /dev/gpiomem

	$ groups
	jan adm dialout cdrom sudo audio video plugdev games users input render netdev gpio i2c spi

	$ cat /etc/systemd/system/apple2driver.service
	[Unit]
	Description=Apple2-IO-RPi Driver

	[Service]
	ExecStart=/home/jan/Apple2-IO-RPi/RaspberryPi/apple2driver/apple2driver
	StandardOutput=journal
	StandardError=journal
	SyslogIdentifier=apple2driver
	User=jan
	Group=jan
	WorkingDirectory=/home/jan/Apple2-IO-RPi/RaspberryPi/apple2driver

	[Install]
	WantedBy=basic.target

Any idea what is wrong?

Thank you very much.

### Hardware Version

Sixth Prototype (Self-assembled)

### Firmware Version

000F

### Driver Version

002B (fix keyboard delay)

### Shell Version

000E (fix hang on exit)

### Where are you seeing this problem?

Boot

### What computer is this running on?

Apple //e (enhanced / platinum)

**Comment by JPT77** [comment]
Solved. 
It was caused by issuing `sudo rpi-update` while doing debian upgrade.
Several guides recommend doing a rpi-update. But one resource tells this fetches current development kernel and firmware blobs which may be unstable. Firmware and kernel updates should be done automatically by the apt packages upgraded. 
I will create a discussion "how to upgrade Rasbian OS"...
